// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmropehesyqmzlqxnbfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcm9wZWhlc3lxbXpscXhuYmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTE4MTQsImV4cCI6MjA3MTQyNzgxNH0.GvGNZyNVTqAPj0nPlxMWPaey1iNwixhHssF37q_5OFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});